- name: frontend
  hosts: all
  become: true
  tasks:
    - name: install nginx
      ansible.builtin.yum:
        name: nginx
        state: installed
    - name: copy roboshop project
      ansible.builtin.copy:
        src: nginx_roboshop.conf
        dest: /etc/nginx/default.d/roboshop.conf

    - name: delete directory
      ansible.builtin.file:
        path: usr/share/nginx/html
        state: absent

    - name: create directory
      ansible.builtin.file:
        path: usr/share/nginx/html
        state: directory

    - name: download app content
      ansible.builtin.unarchieve:
        src: