- name: mysql
  hosts: all
  become: yes
  tasks:
    - name: mysql repo copying
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: disable default mysql version
      ansible.builtin.shell: dnf module disable mysql -y

    - name: install mysql server
      ansible.builtin.yum:
        name: mysql-community-server
        state: installed

    - name: start mysql service
      ansible.builtin.systemd:
        name: mysqld
        state: restarted
        enabled: yes

    - name: set root password
      ansible.builtin.shell: mysql -uroot -pRoboShop@1

