- name: disable nodejs
  ansible.builtin.shell: dnf module disable nodejs -y

- name: enablenodejs
  ansible.builtin.shell: dnf module enable nodejs:18 -y


- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: app preq
  ansible.builtin.import_tasks: app-preq.yml



- name: download dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: schema setup
  ansible.builtin.import_tasks: mongo-schema.yml
  when: schema is defined


- name: setup {{component}}
  ansible.builtin.import_tasks: systemd.yml

